public enum EventType {
    GASOLINE_LOADED,
    GASOLINE_SELECTED,
    USER_CONFIRMED,
    SERIAL_RECEIVED,
    VALID_CARD_READED,
    DATA_COMPLETE,
    TRANSACTION_REQUEST_INITIATION,
    TRANSACTION_REQUEST_SUCCESS,
    TRANSACTION_REQUEST_NOT_ENOUGH_BALANCE,
    TRANSACTION_REQUEST_ERROR,
    TRANSCATION_REQUEST_RESPONSE_RECEIVED,
    MAX_USAGE_CONTROL,
}